platform :ios, '10.0'

target 'MyApp' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'EXCore', path: '../node_modules/expo-core/ios'
  pod 'EXReactNativeAdapter', path: '../node_modules/expo-react-native-adapter/ios', inhibit_warnings: true
  pod 'EXFontInterface', path: '../node_modules/expo-font-interface/ios'
  pod 'EXImageLoaderInterface', path: '../node_modules/expo-image-loader-interface/ios'
  pod 'EXConstantsInterface', path: '../node_modules/expo-constants-interface/ios'
  pod 'EXSensorsInterface', path: '../node_modules/expo-sensors-interface/ios'
  pod 'EXConstants', path: '../node_modules/expo-constants/ios'
  pod 'EXFileSystem', path: '../node_modules/expo-file-system/ios'
  pod 'EXFileSystemInterface', path: '../node_modules/expo-file-system-interface/ios'
  pod 'EXPermissionsInterface', path: '../node_modules/expo-permissions-interface/ios'
  pod 'EXPermissions', path: '../node_modules/expo-permissions/ios'
  pod 'EXCameraInterface', path: '../node_modules/expo-camera-interface/ios'
  pod 'EXFaceDetectorInterface', path: '../node_modules/expo-face-detector-interface/ios'
  pod 'EXBarCodeScannerInterface', path: '../node_modules/expo-barcode-scanner-interface/ios'
  pod 'EXTaskManagerInterface', path: '../node_modules/expo-task-manager-interface/ios'
  pod 'EXLocalization', path: '../node_modules/expo-localization/ios'
  pod 'EXFont', path: '../node_modules/expo-font/ios'

  target 'MyAppTests' do
    inherit! :search_paths
  end
end
